### ISSUE TITLE
GUI in Ubuntu images

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/linux-image-templates#33]
Hey!

I'd like to start a graphical environment in my ubuntu images. Do I have to do all the manual setup, or is there an easier way? Do you maybe provide Ubuntu Desktop images?

**Comment by edigaryev** [comment]
Unfortunately, we currently don't ship desktop versions of popular Linux distributions because there's not enough demand and they don't have the cloud variants that are much easier to install in an automated fashion.

However, you can easily convert `ghcr.io/cirruslabs/ubuntu:latest` to have GUI with just a single command:

```
sudo apt install ubuntu-desktop
```

Reboot after the installation succeeds, and you'll see something like this:

<img width="1136" alt="Screenshot 2024-08-07 at 17 03 37" src="https://github.com/user-attachments/assets/25e3e9ca-9e92-43d1-9781-3ea21443a139">
